# Generated by Django 5.0.4 on 2024-04-09 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
