# Generated by Django 5.0.4 on 2024-04-09 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0002_alter_pessoa_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
